# https://circleci.com/orbs/registry/orb/circleci/docker
version: 2.1
orbs:
    docker: circleci/docker@0.5.18
workflows:
    build_and_publish_docker_image:
        jobs:
            -   docker/publish:
                    image: itsupcom/docker-symfony
                    tag: "7.4"
                    extra_build_args: '--build-arg PHP_VERSION=7.4'
            -   docker/publish:
                    image: itsupcom/docker-symfony
                    tag: latest
                    extra_build_args: '--build-arg PHP_VERSION=7.4'
